name: Shellcheck

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  code:
    name: Tests and ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: ludeeus/action-shellcheck@0.2.1
